CUDA_VISIBLE_DEVICES="1,3" python3 claim_vrf.py \
--train_data data/cha_macbertlarge_best/train_model.1600.pt.jsonl  \
--test_data data/cha_macbertlarge_best/test_model.1600.pt.jsonl \
--dev_data data/cha_macbertlarge_best/dev_model.1600.pt.jsonl \
--output_file submission_0529_cha_macbert_large.jsonl \
--model_name hfl/chinese-macbert-large \
--exp_name ensemble_macbert_large_dynamic_load_with_cha_step2 \
--test_batch_size 2 \
--train_batch_size 2 \
--validation_step 1600 \
--seed 1335 \
--num_epoch 35 \
--max_seq_len 512 \
--lr 6.5e-5 \
--accumulation_step 32 \
--do_ensemble 1 \
